listen_addresses = '*'
max_connections = 50
shared_buffers = 256MB

fsync = on
full_page_writes = on
synchronous_commit = on
autovacuum = on

shared_preload_libraries = ''
password_encryption = 'scram-sha-256'
log_statement = 'none'
